---
title: "task14"
author: "Dovile Oganauskaite"
date: '2016 m lapkritis 10 d '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Uždavinys:

Ar galima taip pertvarkyti skaičiaus:

a) 9754310

b) 8754310

Skaitmenis, kad gautas skaičius dalytųsi iš 37 ?



Funkcijai permutation reikalinga biblioteka 'combinat'
```{r}
library(combinat)
```
a) 9754310
```{r}
a <- c(9,7,5,4,3,1,0) #sukuriamas vektorius iš visų galimų skaičių ir priskiriamas pavadinimas a
x1 <- permn(a) # sugeneruojami visi galimi deriniai
test1 <- function(a){
   s = as.numeric(paste(a, collapse = ""))
   s %% 37 == 0
 }

y1 = sapply(x1, test1)
y1 #pateikiami TRUE ir FALSE
sum(y1 == TRUE) #suskaičiuojama, kiek yra derinių, kurie dalinasi iš 37

```
b) 8754310
```{r}
b <- c(8,7,5,4,3,1,0) #sukuriamas vektorius iš visų galimų skaičių ir priskiriamas pavadinimas a
x2 <- permn(b) # sugeneruojami visi galimi deriniai
test2 <- function(b){
   s = as.numeric(paste(b, collapse = ""))
   s %% 37 == 0
 }

y2 = sapply(x2, test2)
y2 #pateikiami TRUE ir FALSE
sum(y2 == TRUE) #suskaičiuojama, kiek yra derinių, kurie dalinasi iš 37
```

